version: "3.7"

services:
    login-api:
      image: login-api-image:latest
      ports:
        - 8001:8080
      depends_on:
        - login-db  

    blocklist-api:
      image: blocklist-api-image:latest
      ports:
        - 8002:80

    card-request-api:
      image: card-request-api-image:latest
      ports:
          - 8003:80
      depends_on:
          - card-request-db
          - blocklist-api  

    login-db:
      image: 'mysql:latest'
      volumes:
        - login-db-volume:/var/lib/mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: login_database
        MYSQL_HOST: localhost   

    card-request-db:
      image: 'mysql:latest'
      volumes:
       - card-request-db-volume:/var/lib/mysql
      ports:
       - 3308:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: card_request_database
        MYSQL_HOST: localhost      

    
    adminer:
      image: adminer
      restart: always
      ports: 
        - 8081:8080

volumes:
  login-db-volume:
  card-request-db-volume: