version: "3.7"

services:
    login-api:
      image: login-api:latest
      ports:
        - 8001:8080
      depends_on:
        - login-db
      environment:
        DB_URL: jdbc:mysql://login-db:3306/login_database
        DB_USER: user
        DB_PASSWORD: user    

    blocklist-api:
      image: blocklist-api:latest
      ports:
        - 8002:80

    card-request-api:
      image: card-request-api:latest
      ports:
          - 8004:8080
      depends_on:
          - card-request-db
          - blocklist-api  
      environment:
        DB_URL: jdbc:mysql://card-request-db:3306/card_request_database
        DB_USER: user
        DB_PASSWORD: user
        INITIAL_TIME_SCHEDULED: 30000
        PERIODIC_TIME_SCHEDULED: 60000
        LOGIN_URL: http://login-api:8080
        BLOCKLIST_URL: http://blocklist-api:80     

    login-db:
      image: 'mysql:latest'
      volumes:
        - login-db-volume:/var/lib/mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: login_database        

    card-request-db:
      image: 'mysql:latest'
      volumes:
       - card-request-db-volume:/var/lib/mysql
      ports:
       - 3308:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: card_request_database       
    
    adminer:
      image: adminer
      restart: always
      ports: 
        - 8081:8080

volumes:
  login-db-volume:
  card-request-db-volume: