version: "3.7"

services:
    login-api:
      image: login-api-image:latest
      ports:
        - 8001:8080

    blocklist-api:
      image: blocklist-api-image:latest
      ports:
        - 8002:80

    card-request-api:
      image: card-request-api-image:latest
      ports:
          - 8003:80

    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gnb_database
        MYSQL_USER: user
        MYSQL_PASSWORD: user    
      volumes:
        - ./docker/mysql/data:/var/lib/mysql:rw
        - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    
    adminer:
      image: adminer
      restart: always
      ports: 
        - 8081:8080        